language: node_js
cache:
  npm: false
node_js:
- lts/*
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: HRyIDWHQzP9yuXjzmekUtnNsSwFG8tGEOi76pIuyyFBVZMXlhF9+nJbIpTvTK7ZpzlXcWSy7dq0UTDMjErkUPCm7NfOaUPBMQBdXupGMImj70y5i3bb2Mo9BxpWZVC38fGgCVpLmyLAnvcur11AId3sWYFB4qy5xhGOh3xyP2WIeiuBpWPfX+CfT9OIu4xRRvfePDo8Oubrre9Z38whXCnzwbi3zEpKLyor8q6Vm7xYInnMKzI68uimXHRgyXquQcJ0Vl31Rr86G9fzhXUojM98/2066uBK+mzm+2xNC0pXs8N0V4SOSThUXu5NE6AQxpLlrz5QaJhDJr/mrPcGCHSNN7TQq4gHeH6ISxHz3+ewxXI+8wIUSteJRf3/PmVNtpc8+cFtHuffRaUrdoJLjn0qWPuE0SRp+5a7GHkFdOKszyEBv4Nmscb2kp0VZVXaI5l1D4YWMxHI4vtiZc75IbYuaNBlho5Ist6zDqU29ysa0qUnv3aUDrTPzdwFq0ELseL8mewXLN9cWGkStkFqTLbSYKEasSor/22Rqd/tB7/AvFsCrOUYSXeFrdhwnoMLGs8H/1nkhLnZthHBV2XRCFvUh9jpPEMP8vyQiw0cMA/oaNnNBYmvWdRAYlXO8BwL+UuM7EAJRIIVwsn1cJ4npAA9uSabuEnSrfk10FIKwWD8=
