language: node_js
cache:
  npm: false
node_js:
- lts/*
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: hv/FQcpG82bcau68yDbZYMY3ifdtqP2Rx5ZWibvjAYysR1YQe4m7hKs6IDxx9YvFHGMQc5V8JnLEVAkjg6FynL+cTpM5UM4983vv7eneTRIb3XK39dbcvZgZhH/T9dfY+Hodkij3GcLGcUyxm0LS2vOM9JozDGroHhN4VjAUib3rkLLaX88zBSdCPWLFQV3wJU3Wk9u5ddosC4iV5I56Jk7+X0to+aflS0oS3xiOybYdzVKYwWHxGOBpJhQs43vMOwbxY+5ao/EcTMGy/fb/VJNaH2KSkr/v0kB3SsmW2q/W7CFIp6F5AZt5me2bLZlFwo17z9RS6oB5jR9PbdOysOo+V+8RStqRTwUlBhiDPIffpZdQZajwHVea/1R2k3fW+JOgPmsqfb39/OGM9bEI7A4iv6WwGxShEF1ZJCwJSEWNMemSKfWBAul1M9SIUzUhrUo7r0DwJR/P5/jrqR82or1LnheS2RSlQRNOME1dItisjStPuH0ojPSztcrnmElE1fAGOZBCKRDJuWdbd1aAPaKIbSL4cR0UP2eJzTCy2Y0L/uYu/BQgwTDbJA+7cCrxKbYv46r2gZR3Hljw5WnCMnaxUHUutEDLR0O1rn+nU5oJxiVjr5fQvJfTqnR0be43TtcOL5Q+ELOIhMceuJ0aYc3MRVCohcDJL/m+dNyQ0C8=
